### ISSUE TITLE
Overlapping tick labels on x axis

### ISSUE THREAD

**Issue by mtazzari** [aplpy/aplpy#258]
I am struggling to make the x-axis tick labels readable, i.e. not to have them overlapping (see attachment). I have looked in the aplpy API, but unlike matplotlib, the aplpy.TickLabels class seems not to offer any specific option to manually set the tick labels. Here is the reference I looked into https://aplpy.readthedocs.org/en/stable/api/aplpy.TickLabels.html#aplpy.TickLabels .

I have tried to work around this issue by tweaking the xlimits, but without success.

Have you ever stumbled upon this? Any clue how to resolve this?

Many thanks in advance!

PS. For reference, to set the ticks' labels in matplotlib I usually use:

    fig, ax = plt.subplots()
    ax.set_yticks(yticks)  # to set the ticks location
    ax.set_yticklabels(yticks_labels)  # to set the tick labels

![prova](https://cloud.githubusercontent.com/assets/6020226/7462848/eb5cd3b0-f2b4-11e4-921b-042f9bf9f7c8.png)

**Comment by astrofrog** [comment]
@mdboom - there are two things you can do to help with this kind of situation: increase the tick spacing, or reduce the font. For the first, you can use ``f.ticks.set_xspacing`` (spacing should be in degrees, not hours) and for the font, ``f.tick_labels.set_font``. Let me know if you have issues with either.

**Comment by mtazzari** [comment]
I would keep the font size unchanged for better paper-readability.
So I have tried changing the x_spacing. I have been able to produce the attached figure using

    f.ticks.set_xspacing(0.0005) # number in degrees

The figure is better, however I noticed that I can only pick multiple values of 0.0005 for the spacing. For instance, if I use 0.0006 or 0.0007, it simply reverts to the 'auto' spacing, thus producing the overlapping labels as before.
I digged in the aplpy ticks.py module but I have not been able to figure out why it does not work with 0.0006 or 0.0007.  
![fftau_maps_1 mm](https://cloud.githubusercontent.com/assets/6020226/7470699/779ef352-f31f-11e4-87da-3a555d489d17.png)

**Comment by astrofrog** [comment]
@mtazzari - the reason it doesn't work is because the spacing needs to be a multiple of the spacing that can be represented by the label format. So if you are using hh:mm:ss.ss then the smallest unit of tick angle is 0.01 second = 0.15 arcseconds. Therefore the tick spacing should be a multiple of 0.15 / 3600. So for example, 0.000375 and 0.00075 should work (more generally, n * 0.15 / 3600). Does that help?

**Comment by mtazzari** [comment]
This is great!! I was slowly coming to the same reasoning... Yes, your statement is very clear. I have tried with both 0.000375 and 0.00075 and it works perfectly. Many thanks for the extremely quick (and resolutive) support!
I attach figure made with 0.00075.
![fftau_maps_1 mm](https://cloud.githubusercontent.com/assets/6020226/7471282/5d717f6c-f325-11e4-9d5e-4e3b1d9d2d26.png)

**Comment by keflavich** [comment]
@astrofrog I'd like to reopen this issue, as I have the same problem but I don't want to reduce the # of ticks.   Is it possible, instead, to have the `4h23m` (in Marco's example), show up on the left side instead of the right side?  I'm not sure exactly where to hack this in aplpy, but I'll submit a PR if & when I find it.
