### ISSUE TITLE
handle regridding in make_rgb_image

### ISSUE THREAD

**Issue by Joshuaalbert** [aplpy/aplpy#334]
As it stands, when three different shaped fits files are given to make_rgb_image one gets "TypeError: can't handle data type".
To handle this there are a number of useful functions built right here:
http://fits-tools.readthedocs.io/en/latest/fits_tools.html

Most useful in this feature would be to match the wcs's during regridding of each fits (when not passing in a single fits cube which should already likely be matched).

I understand this enhancement isn't urgent, because a user can do this on their own, but it would be a nice extra.

**Comment by astrofrog** [comment]
@Joshuaalbert - you can already do this by calling ``make_rgb_cube`` then ``make_rgb_image``, though maybe we could streamline things to avoid the two calls. The reason this was done in two steps is because the regridding can be quite slow dependending on the image, so the idea is to make it easier to tweak RGB settings without having to redo the reprojection.

**Comment by astrofrog** [comment]
I'm going to close this since it should all work fine via ``make_rgb_cube``.
