### ISSUE TITLE
problem in plotting FIRST image 

### ISSUE THREAD

**Issue by suvenduat** [aplpy/aplpy#372]
Hi, I have downloaded a FIRST image (https://third.ucllnl.org/cgi-bin/firstcutout) and trying to plot it using Aplpy with the following command:

import aplpy 
fig = aplpy.FITSFigure('firstcutout.fits')

but it fails with IndexError: list index out of range

Please let me know how to solve this problem.

**Comment by Sunmish** [comment]
I suspect this is because the FIRST images have NAXIS=2, but have coordinate/WCS parameters (CDELT, CRVAL, etc) for a third and fourth axis (frequency and Stokes, in this case). If you delete the additional keys corresponding to the third and fourth axis aplpy will happily make an image. 

E.g. something like this is a rough workaround if opening the HDUList first with astropy,
```
for i in ["3", "4"]:
    for j in ["CRVAL"+i, "CTYPE"+i, "CDELT"+i, "CRPIX"+i, "CUNIT"+i, "CROTA"+i]:
        del hdulist[0].header[j]
```

**Comment by suvenduat** [comment]
Thanks, this works. But the axis is in pixel and I am unable to plot them in wcs.
fig = aplpy.FITSFigure(hdulist[0].data, hdu= hdulist[0].header)
what should I modify?

**Comment by Sunmish** [comment]
The first argument should just be ```hdulist``` in this case. The ```hdu``` parameter is 0 in this case, which is the default option. So try:

```python
fig = aplpy.FITSFigure(hdulist)
```

**Comment by suvenduat** [comment]
Thanks...works perfectly.
