### ISSUE TITLE
Blank image in Python 2.7

### ISSUE THREAD

**Issue by Mixpap** [aplpy/aplpy#398]
I tried to make a plot from an astroquery Ned Fits file, but the output is blank (in a Jupyter notebook but also if a save the figure)
I tried every possible combination of data input in ```FITSFigure```.
```python
import aplpy
from astroquery.ned import Ned

image_list=Ned.get_images('PKS0011-046') #for example
image=image_list[0]
#image is [<astropy.io.fits.hdu.image.PrimaryHDU object at 0x7fface82e350>]
aplpy_image=aplpy.FITSFigure(image)
aplpy_image=aplpy.FITSFigure(image[0])
#aplpy_image=aplpy.FITSFigure(image[0].data)
```
If i try to plot the image[0].data array through matplotlibs imshow i get the image 
```python
import matplotlib.pyplot as plt
plt.imshow(image[0].data)
```
Out:
![test_m](https://user-images.githubusercontent.com/10127931/44658745-82768380-aa0a-11e8-9d80-ee4d5ecf50b3.png)

python version 2.7.13
aplpy version 1.1.1
astropy version 2.0.6
matplotlib version 2.2.3

Am i missing something?

**Comment by Sunmish** [comment]
To show the colormap you need to call [`show_colorscale()`](https://aplpy.readthedocs.io/en/stable/api/aplpy.FITSFigure.html#aplpy.FITSFigure.show_colorscale) (or  [`show_grayscale()`](https://aplpy.readthedocs.io/en/stable/api/aplpy.FITSFigure.html#aplpy.FITSFigure.show_grayscale)) otherwise the image will just appear as a set of axes.

E.g., in your code you could write:
```
aplpy_image = aplpy.FITSFigure(image)
aplpy_image.show_colorscale()
aplpy_image.savefig("image.png")
```

Additional options can passed to `show_colorscale()` or `show_grayscale()` to change the way the map is displayed.

**Comment by Mixpap** [comment]
Thanks for the reply this works :),
but only if i pass in a single cell (i use it in a jupyter notebook) the ```FITSFigure(image)``` function along with the ```.show_colorscale()``` (or whatever) function.

I don't understand why is better to work like this, rather in a single function or a function that updates the plot.

**Comment by astrofrog** [comment]
@Mixpap - good to know it works now. The fact you have to put them in the same cell is normal Matplotlib behavior, so I will keep it as is.
